In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 맷플롯립 한글 사용 가능
import matplotlib.pyplot as plt
plt.rcParams['font.family'] ='Malgun Gothic'
plt.rcParams['axes.unicode_minus'] =False

In [3]:
num_df = pd.read_csv('Data_Preprocessing/apt_all_numeric_information.csv')
time_df = pd.read_csv('forDP/apt_Q1234_season.csv')

In [10]:
num_df

,NO,latitude,longitude,brand_label_encoded,exclusive_area_m2,apt_age,floor,closest_station_dist_km,station_score,closest_bus_stop_dist_km,...,의류_신발_지출_총금액_퍼센트,생활용품_지출_총금액_퍼센트,의료비_지출_총금액_퍼센트,교통_지출_총금액_퍼센트,교육_지출_총금액_퍼센트,유흥_지출_총금액_퍼센트,여가_문화_지출_총금액_퍼센트,기타_지출_총금액_퍼센트,음식_지출_총금액_퍼센트,adjusted_price
0,2019_00001,37.569626,127.041530,1.0,134.790,21.0,17.0,0.424043,37.0,0.177642,...,0.221316,0.444569,5.659943,27.585510,1.771718,2.108846,1.589519,6.372794,17.238556,98701.510
1,2019_00002,37.589283,127.072500,1.0,84.980,21.0,9.0,0.744368,6.0,0.139833,...,1.756252,28.301529,17.318916,22.802256,2.045454,2.243247,0.570275,1.396219,11.528192,53612.863
2,2019_00003,37.574608,127.060130,1.0,59.740,19.0,21.0,1.202503,2.0,0.214918,...,1.104262,0.859998,18.788939,27.459848,3.917857,3.759896,2.967879,1.806848,15.298308,61127.637
3,2019_00004,37.616688,127.001840,1.0,71.500,42.0,2.0,0.878108,6.0,0.147962,...,0.739272,0.761183,13.550672,20.879032,4.367771,2.411336,4.570751,2.282742,22.030340,36115.777
4,2019_00005,37.576340,127.074570,4.0,59.928,12.0,12.0,1.384233,1.0,0.208758,...,2.139838,2.284715,11.248837,1.664376,5.776041,5.644256,5.347571,1.895059,24.962490,73465.330
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251091,2023_35638,37.617577,126.921090,1.0,14.030,3.0,11.0,0.128525,29.0,0.120574,...,2.315885,2.150250,27.221273,0.549383,2.838015,2.823143,8.683856,3.580762,27.052020,17000.000
251092,2023_35639,37.609110,126.926440,1.0,29.990,2.0,9.0,0.382465,30.0,0.047303,...,2.315885,2.150250,27.221273,0.549383,2.838015,2.823143,8.683856,3.580762,27.052020,40000.000
251093,2023_35640,37.485530,127.084800,1.0,99.790,30.0,6.0,0.210602,12.0,0.179995,...,0.320323,0.783516,56.270382,0.075761,4.715764,0.019887,3.873366,1.900069,13.122928,175000.000
251094,2023_35641,37.485530,127.084800,1.0,99.790,30.0,6.0,0.210602,12.0,0.179995,...,0.320323,0.783516,56.270382,0.075761,4.715764,0.019887,3.873366,1.900069,13.122928,175000.000
251095,2023_35642,37.502390,126.995964,4.0,84.850,14.0,19.0,0.114033,18.0,0.069158,...,0.242866,0.000242,9.639580,0.428233,22.064005,0.008770,4.181308,9.143516,28.556953,300000.000

In [15]:
time_df.columns

Index(['NO', 'Q_1', 'Q_2', 'Q_3', 'Q_4', 'Season_Fall', 'Season_Spring',
       'Season_Summer', 'Season_Winter', 'adjusted_price'],
      dtype='object')

In [17]:
all_df = pd.concat([num_df, time_df[['NO', 'Q_1', 'Q_2', 'Q_3', 'Q_4', 'Season_Fall', 'Season_Spring',
       'Season_Summer', 'Season_Winter']]], axis=1)

In [20]:
all_df = all_df[['NO', 'latitude', 'longitude', 'brand_label_encoded',
       'exclusive_area_m2', 'apt_age', 'floor', 'closest_station_dist_km',
       'station_score', 'closest_bus_stop_dist_km', 'bus_stop_score',
       'closest_school_dist_km', 'school_score', 'closest_hospital_dist_km',
       'hospital_score', 'closest_park_dist_km', 'park_score',
       'ldong_prev_1_month', 'ldong_prev_3_months', 'ldong_prev_6_months',
       'K_progressive_president', 'A_progressive_president',
       'A_progressive_senate', 'A_progressive_house', 'USD_exchange_rate',
       'CNY_exchange_rate', 'JPY_exchange_rate', '한국은행_기준금리', '정부대출금금리',
       '무역금융지원_프로그램대출금리', '영세자영업자지원_프로그램대출금리', '신성장·일자리지원_프로그램대출금리',
       '설비투자지원_프로그램대출금리', '지방중소기업지원_프로그램대출금리', '자금조정_대출금리', '자금조정_예금금리',
       'adjusted_income', '월_평균_소득_금액', '식료품_지출_총금액_퍼센트', '의류_신발_지출_총금액_퍼센트',
       '생활용품_지출_총금액_퍼센트', '의료비_지출_총금액_퍼센트', '교통_지출_총금액_퍼센트', '교육_지출_총금액_퍼센트',
       '유흥_지출_총금액_퍼센트', '여가_문화_지출_총금액_퍼센트', '기타_지출_총금액_퍼센트', '음식_지출_총금액_퍼센트', 
       'Q_1', 'Q_2', 'Q_3', 'Q_4', 'Season_Spring', 'Season_Summer', 'Season_Fall', 'Season_Winter', 
       'adjusted_price']]

In [23]:
all_df.isna().sum()
all_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251096 entries, 0 to 251095
Data columns (total 58 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   NO                        251096 non-null  object
 1   NO                        251096 non-null  object
 2   latitude                  251096 non-null  float64
 3   longitude                 251096 non-null  float64
 4   brand_label_encoded       251096 non-null  float64
 5   exclusive_area_m2         251096 non-null  float64
 6   apt_age                   251096 non-null  float64
 7   floor                     251096 non-null  float64
 8   closest_station_dist_km   251096 non-null  float64
 9   station_score             251096 non-null  float64
 10  closest_bus_stop_dist_km  251096 non-null  float64
 11  bus_stop_score            251096 non-null  float64
 12  closest_school_dist_km    251096 non-null  float64
 13  school_score              251096 non-null  float64
 14  closest_hospital_dist_km  251096 non-null  float64
 15  hospital_score            251096 non-null  float64
 16  closest_park_dist_km      251096 non-null  float64
 17  park_score                251096 non-null  float64
 18  ldong_prev_1_month        251096 non-null  float64
 19  ldong_prev_3_months       251096 non-null  float64
 20  ldong_prev_6_months       251096 non-null  float64
 21  K_progressive_president   251096 non-null  float64
 22  A_progressive_president   251096 non-null  float64
 23  A_progressive_senate      251096 non-null  float64
 24  A_progressive_house       251096 non-null  float64
 25  USD_exchange_rate         251096 non-null  float64
 26  CNY_exchange_rate         251096 non-null  float64
 27  JPY_exchange_rate         251096 non-null  float64
 28  한국은행_기준금리                 251096 non-null  float64
 29  정부대출금금리                   251096 non-null  float64
 30  무역금융지원_프로그램대출금리           251096 non-null  float64
 31  영세자영업자지원_프로그램대출금리         251096 non-null  float64
 32  신성장·일자리지원_프로그램대출금리        251096 non-null  float64
 33  설비투자지원_프로그램대출금리           251096 non-null  float64
 34  지방중소기업지원_프로그램대출금리         251096 non-null  float64
 35  자금조정_대출금리                 251096 non-null  float64
 36  자금조정_예금금리                 251096 non-null  float64
 37  adjusted_income           251096 non-null  float64
 38  월_평균_소득_금액                251096 non-null  float64
 39  식료품_지출_총금액_퍼센트            251096 non-null  float64
 40  의류_신발_지출_총금액_퍼센트          251096 non-null  float64
 41  생활용품_지출_총금액_퍼센트           251096 non-null  float64
 42  의료비_지출_총금액_퍼센트            251096 non-null  float64
 43  교통_지출_총금액_퍼센트             251096 non-null  float64
 44  교육_지출_총금액_퍼센트             251096 non-null  float64
 45  유흥_지출_총금액_퍼센트             251096 non-null  float64
 46  여가_문화_지출_총금액_퍼센트          251096 non-null  float64
 47  기타_지출_총금액_퍼센트             251096 non-null  float64
 48  음식_지출_총금액_퍼센트             251096 non-null  float64
 49  Q_1                       251096 non-null  bool
 50  Q_2                       251096 non-null  bool
 51  Q_3                       251096 non-null  bool
 52  Q_4                       251096 non-null  bool
 53  Season_Spring             251096 non-null  bool
 54  Season_Summer             251096 non-null  bool
 55  Season_Fall               251096 non-null  bool
 56  Season_Winter             251096 non-null  bool
 57  adjusted_price            251096 non-null  float64
dtypes: bool(8), float64(48), object(2)
memory usage: 97.7+ MB

In [24]:
all_df.to_csv('Data_Preprocessing/num_data.csv', index=False, encoding='utf-8')